version: "3.8"

services:

  account-db:
    image: postgres:16
    container_name: account-db
    environment:
      - POSTGRES_DB=${ACCOUNT_DB}
      - POSTGRES_USER=${ACCOUNT_DB_USER}
      - POSTGRES_PASSWORD=${ACCOUNT_DB_PASSWORD}
    ports:
      - "${ACCOUNT_DB_PORT}:5432"
    volumes:
      - account_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    ports:
      - "${KEYCLOAK_DB_PORT}:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HTTP_ENABLED=true
      - KC_LOG_LEVEL=INFO
      - KC_METRICS_ENABLED=false
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME_URL=http://localhost:${KEYCLOAK_PORT}
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start-dev
      - --import-realm
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-db
    restart: unless-stopped

  account-service:
    build:
      context: AccountService/
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "${ACCOUNT_SERVICE_PORT}:80"
    depends_on:
      - keycloak
      - account-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Authentication__AuthenticationServerUrl=${AUTHENTICATION_SERVER_URL}
      - Authentication__Audience=${AUDIENCE}
      - Authentication__Realm=${REALM}
      - Authentication__AdminUsername=${KEYCLOAK_ADMIN}
      - Authentication__AdminPassword=${KEYCLOAK_ADMIN_PASSWORD}
      - ConnectionStrings__DefaultConnection=Host=account-db;Database=${ACCOUNT_DB};Username=${ACCOUNT_DB_USER};Password=${ACCOUNT_DB_PASSWORD}
    restart: unless-stopped

volumes:
  account_data:
  keycloak_data:
